version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:latest
    ports:
      - "6380:6379" 

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.core.celery.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - celery
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
